version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - PORT=5000
    depends_on:
      - mongo
    restart: always

  mongo:
    build: ./mongo
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:

