name: Build and push image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_PASSWORD }}

      - name: Extract and save the Commit ID
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo $IMAGE_TAG

      # 3️⃣ Build and Push Backend
      - name: Build image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/frontend-app:${IMAGE_TAG} ./frontend 
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/backend-app:$IMAGE_TAG ./backend
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/mongo-app:$IMAGE_TAG ./mongo

      - name: Push image to Docker Hub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/frontend-app:$IMAGE_TAG
          docker push ${{secrets.DOCKERHUB_USERNAME}}/backend-app:$IMAGE_TAG
          docker push ${{secrets.DOCKERHUB_USERNAME}}/mongo-app:$IMAGE_TAG
