name: Build and Push Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: "Path to the .tfvars file"
        required: true
        default: "terraform.tfvars"
      action:
        type: choice
        description: "Defines the terraform Actions"
        options:
          - plan
          - apply
          - destroy
        default: "plan"

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME }}
          password: ${{secrets.DOCKERHUB_PASSWORD }}

      - name: Extract and save the Commit ID
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Print the commit ID
        run: |
          echo "IMAGE TAG IS $IMAGE_TAG"
          echo "GITHUB ENV IS $GITHUB_ENV"

      # 3️⃣ Build and Push Backend
      - name: Build image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/frontend-app:$IMAGE_TAG ./frontend 
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/backend-app:$IMAGE_TAG ./backend
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/mongo-app:$IMAGE_TAG ./mongo

      - name: Push image to Docker Hub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/frontend-app:$IMAGE_TAG
          docker push ${{secrets.DOCKERHUB_USERNAME}}/backend-app:$IMAGE_TAG
          docker push ${{secrets.DOCKERHUB_USERNAME}}/mongo-app:$IMAGE_TAG

  terraform:
    name: Terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    needs: build
    steps:
      # 1️⃣ Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: |
          terraform plan -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          terraform destroy -auto-approve -var-file=${{ github.event.inputs.tfvars_file }} -input=false
